import { HiOutlineVideoCamera } from 'react-icons/hi2'
import { RiGalleryFill } from 'react-icons/ri'

const AssetsAPI = [
    {
        id: 1,
        Image: '../../../Assets/video1.png',
        icon: <HiOutlineVideoCamera className='bg-primary text-white text-3xl p-3 rounded-full min-w-[60px] min-h-[60px] border-4 border-white border-solid shadow-primary  hover:bg-SlateBlue cursor-pointer' />,
        category: 'video',
        size: '1280*832',
        storage: '155KB',
        vtitle: 'Ships From Warehouse',
        vdetails: 'Uploaded by  Johan Jun 5, 2023, 8:01 PM Video',
    },
    {
        id: 2,
        Image: '../../../Assets/video2.png',
        icon: <HiOutlineVideoCamera className='bg-primary text-white text-3xl p-3 rounded-full min-w-[60px] min-h-[60px] border-4 border-white border-solid shadow-primary hover:bg-SlateBlue cursor-pointer ' />,
        category: 'video',
        size: '1280*832',
        storage: '155KB',
        vtitle: 'Ships From Warehouse',
        vdetails: 'Uploaded by  Johan Jun 5, 2023, 8:01 PM Video',

    },
    {
        id: 3,
        Image: '../../../Assets/video3.png',
        icon: <HiOutlineVideoCamera className='bg-primary text-white text-3xl p-3 rounded-full min-w-[60px] min-h-[60px] border-4 border-white border-solid shadow-primary hover:bg-SlateBlue cursor-pointer ' />,
        category: 'video',
        size: '1280*832',
        storage: '155KB',
        vtitle: 'Ships From Warehouse',
        vdetails: 'Uploaded by  Johan Jun 5, 2023, 8:01 PM Video',
    },
    {
        id: 4,
        Image: '../../../Assets/image83.png',
        icon: <RiGalleryFill className='bg-primary text-white text-3xl p-3 rounded-full min-w-[60px] min-h-[60px] border-4 border-white border-solid shadow-primary hover:bg-SlateBlue cursor-pointer ' />,
        // title: 'Purchase Securely',
        // subtitle: 'Image',
        category: 'image',
        size: '1280*832',
        storage: '155KB',
        vtitle: 'Ships From Warehouse',
        vdetails: 'Uploaded by  Johan Jun 5, 2023, 8:01 PM Video',
    },
    {
        id: 5,
        Image: '../../../Assets/image84.png',
        icon: <RiGalleryFill className='bg-primary text-white text-3xl p-3 rounded-full min-w-[60px] min-h-[60px] border-4 border-white border-solid shadow-primary hover:bg-SlateBlue cursor-pointer ' />,
        // title: 'Purchase Securely',
        // subtitle: 'Image',
        category: 'image',
        size: '1280*832',
        storage: '155KB',
        vtitle: 'Ships From Warehouse',
        vdetails: 'Uploaded by  Johan Jun 5, 2023, 8:01 PM Video',
    },
    {
        id: 6,
        Image: '../../../Assets/image86.png',
        icon: <RiGalleryFill className='bg-primary text-white text-3xl p-3 rounded-full min-w-[60px] min-h-[60px] border-4 border-white border-solid shadow-primary hover:bg-SlateBlue cursor-pointer ' />,
        // title: 'Purchase Securely',
        // subtitle: 'Image',
        category: 'image',
        size: '1280*832',
        storage: '155KB',
        vtitle: 'Ships From Warehouse',
        vdetails: 'Uploaded by  Johan Jun 5, 2023, 8:01 PM Video',
    },
]
export default AssetsAPI